Update macOS package building scripts to allow exclusion of components like themes, prefpane/updater, RC scripts, and legacy firmware

diff --git a/CloverPackage/makepkg b/CloverPackage/makepkg
--- a/CloverPackage/makepkg
+++ b/CloverPackage/makepkg
@@ -1,7 +1,30 @@
 #!/bin/bash
 #
 # Reset default charset for GNUsed problems...
+#set -x
 export LC_ALL=C
+
+usage () {
+printf "\n\e[1m%s\e[0m\n" "Usage: $0 [flag1 flag2...]"
+printf "\n%s" "The (optional) exclude flags are being passed to the buildpkg.sh script, when specified."
+printf "\n%s\n" "Possible flag values:"
+printf "\n\e[1m%s\e[0m\t%s" "--nothemes" "Excludes the Themes subpackage."
+printf "\n\e[1m%s\e[0m\t%s" "--noprefpane" "Excludes the Clover Prefpane / Clover Updater subpackage."
+printf "\n\e[1m%s\e[0m\t\t%s" "--norc" "Excludes the RC scripts subpackage."
+printf "\n\e[1m%s\e[0m\t%s" "--nolegacy" "Excludes the CloverEFI subpackages."
+echo
+}
+
+while [[ $# -gt 0 ]]; do
+	case "${1}" in
+		--nothemes ) NOEXTRAS+=" --nothemes";;
+		--noprefpane ) NOEXTRAS+=" --noprefpane";;
+		--norc ) NOEXTRAS+=" --norc";;
+		--nolegacy ) NOEXTRAS+=" --nolegacy";;
+		* ) printf "\e[1m%s\e[0m\n" "Invalid option: ${1} !"; usage; exit 1;;
+	esac
+	shift
+done
 
 # Workspace = edk2/Clover/CloverPackage
 
@@ -58,7 +81,7 @@ fi
 
 # Start to build installer.
 
-package/buildpkg.sh "$SRCROOT" "sym" "$PKG_BUILD_DIR" "$1" || exit $?
+package/buildpkg.sh --srcroot "$SRCROOT" --symroot "sym" --builddir "$PKG_BUILD_DIR" ${NOEXTRAS:1} || exit $?
 
 (cd sym ; zip Clover_${version}_r${revision}.zip \
  Clover_${version}_r${revision}.pkg              \
@@ -72,10 +95,8 @@ rm -f  revision
 
 # Workspace = edk2/Clover/CloverPackage
 # Open the final folder.
-#if [ "$1" == "" ]; then
 ls -la sym
 open sym
-#fi
 # Finish building installer.
 
 exit 0
