Update Clover preference pane
* Add Clover.BackupDirOnDestVol variable to force the backup directory
  to be created on destination volume instead of EFI volume.
* Add Clover.KeepBackupLimit variable to limit the number of backup to
  keep.

diff --git a/CloverPackage/package/Scripts.templates/EFIFolder/preinstall b/CloverPackage/package/Scripts.templates/EFIFolder/preinstall
--- a/CloverPackage/package/Scripts.templates/EFIFolder/preinstall
+++ b/CloverPackage/package/Scripts.templates/EFIFolder/preinstall
@@ -35,6 +35,24 @@ install_log="${DEST_VOL}/Clover_Install_Log.txt"
 plistbuddy='/usr/libexec/PlistBuddy'
 installer_target_esp_refid='@INSTALLER_TARGET_ESP_REFID@'
 
+#
+# get value of a nvram key
+#
+GetNVRamKey() {
+    # Arguments:
+    #    $1: nvram key to search (case insensitive)
+    # Return:
+    #    return the value of the nvram key
+    #    exit code is != 0 if the nvram key wasn't found
+    local keyvalue exitCode
+    local IFS=$(printf "\t")
+    keyvalue=( $(/usr/sbin/nvram -p | /usr/bin/grep -i "^${1}\t*" 2>/dev/null) )
+    exitCode=$?
+    [[ $exitCode -eq 0 ]] && echo "${keyvalue[1]}"
+    return $exitCode
+}
+export -f GetNVRamKey
+
 # ---------------------------------------------
 # Creating log file
 # ---------------------------------------------
@@ -70,56 +88,69 @@ for cloverfile in BOOT/BOOTX64.efi CLOVER/CLOVERX64.efi CLOVER/CLOVERIA32.efi; d
 	fi
 done
 
-backupRootDir="$EFI_ROOT_DIR/EFI-Backups"
+backupDirOnDestVol=$(GetNVRamKey 'Clover.BackupDirOnDestVol')
+if [[ "$backupDirOnDestVol" =~ Y|y ]]; then
+	backupRootDir="$DEST_VOL/EFI-Backups" # backup on destination volume
+else
+	backupRootDir="$EFI_ROOT_DIR/EFI-Backups" # default
+fi
 backupDir="${backupRootDir}/$old_revision/"$( date -j "+%F-%Hh%M" )
 
-# Create the backup dirextory
-mkdir -p "$backupDir"
-
-
-# ---------------------------------------------
-# Backing up Clover files
-# ---------------------------------------------
-
-echo "" > "$install_log"
-echo "Clover EFI installer log - $( date )" >> "$install_log"
-echo "Installer version: %CLOVERVERSION% r%CLOVERREVISION% EFI bootloader" >> "$install_log"
-echo "======================================================" >> "$install_log"
-diskutil list >> "$install_log"
-
-echo "======================================================" >> "$install_log"
-echo "Backing up EFI files" >> "$install_log"
-echo "" >> "$install_log"
-
-# Backup stage2
-if [ -f "$EFI_ROOT_DIR/boot" ];then
-    echo "Backing up stage2 file $EFI_ROOT_DIR/boot  to ${backupDir}/boot" >> "$install_log"
-    cp -p "$EFI_ROOT_DIR/boot" "${backupDir}/boot"
-fi
-if [ -f "$EFI_ROOT_DIR/boot1" ];then
-    echo "Backing up stage2 file $EFI_ROOT_DIR/boot1 to ${backupDir}/boot1" >> "$install_log"
-    cp -p "$EFI_ROOT_DIR/boot1" "${backupDir}/boot1"
-fi
-if [ -f "$EFI_ROOT_DIR/boot3" ];then
-    echo "Backing up stage2 file $EFI_ROOT_DIR/boot3 to ${backupDir}/boot3" >> "$install_log"
-    cp -p "$EFI_ROOT_DIR/boot3" "${backupDir}/boot3"
-fi
-if [ -f "$EFI_ROOT_DIR/boot6" ];then
-    echo "Backing up stage2 file $EFI_ROOT_DIR/boot6 to ${backupDir}/boot6" >> "$install_log"
-    cp -p "$EFI_ROOT_DIR/boot6" "${backupDir}/boot6"
+keepBackupLimit=$(GetNVRamKey 'Clover.KeepBackupLimit')
+# Remove old backup directories if needed
+if [[ "$keepBackupLimit" =~ [[:digit:]]+ ]]; then
+	index=1
+	while IFS= read -r -u3 -d $'\n' dir ;do # 'fix xemacs fontification
+		if [[ "$index" -ge "$keepBackupLimit" ]]; then
+			rm -rf "$dir"
+		fi
+		(( index++ ))
+	done 3< <(find "$backupRootDir" -type d -depth 2 2>/dev/null | tail -r)
 fi
 
-# Backup /EFI directory
-if [ -d "$EFI_ROOT_DIR/EFI" ];then
-    echo "Backing up $EFI_ROOT_DIR/EFI folder to ${backupDir}/EFI"   >> "$install_log"
-    cp -pR "$EFI_ROOT_DIR/EFI" "${backupDir}/EFI"
-fi
+if [[ -z "$keepBackupLimit" || "$keepBackupLimit" -ne 0 ]]; then
+    # ---------------------------------------------
+    # Backing up Clover files
+    # ---------------------------------------------
 
-chflags -R nohidden "$backupDir" # Remove the invisible flag of files in the backups
+    # Create the backup directory
+    mkdir -p "$backupDir"
+
+    echo "======================================================" >> "$install_log"
+    echo "Backing up EFI files" >> "$install_log"
+    echo "" >> "$install_log"
+
+    # Backup stage2
+    if [ -f "$EFI_ROOT_DIR/boot" ];then
+        echo "Backing up stage2 file $EFI_ROOT_DIR/boot  to ${backupDir}/boot" >> "$install_log"
+        cp -p "$EFI_ROOT_DIR/boot" "${backupDir}/boot"
+    fi
+    if [ -f "$EFI_ROOT_DIR/boot1" ];then
+        echo "Backing up stage2 file $EFI_ROOT_DIR/boot1 to ${backupDir}/boot1" >> "$install_log"
+        cp -p "$EFI_ROOT_DIR/boot1" "${backupDir}/boot1"
+    fi
+    if [ -f "$EFI_ROOT_DIR/boot3" ];then
+        echo "Backing up stage2 file $EFI_ROOT_DIR/boot3 to ${backupDir}/boot3" >> "$install_log"
+        cp -p "$EFI_ROOT_DIR/boot3" "${backupDir}/boot3"
+    fi
+    if [ -f "$EFI_ROOT_DIR/boot6" ];then
+        echo "Backing up stage2 file $EFI_ROOT_DIR/boot6 to ${backupDir}/boot6" >> "$install_log"
+        cp -p "$EFI_ROOT_DIR/boot6" "${backupDir}/boot6"
+    fi
+
+    # Backup /EFI directory
+    if [ -d "$EFI_ROOT_DIR/EFI" ];then
+        echo "Backing up $EFI_ROOT_DIR/EFI folder to ${backupDir}/EFI"   >> "$install_log"
+        cp -pR "$EFI_ROOT_DIR/EFI" "${backupDir}/EFI"
+    fi
+
+    chflags -R nohidden "$backupDir" # Remove the invisible flag of files in the backups
+
+fi
 
 # Remove empty directories
-find "$backupRootDir" -type d -maxdepth 2 -empty -print0 | xargs -0 rmdir
-find "$backupRootDir" -type d -maxdepth 1 -empty -print0 | xargs -0 rmdir
+find "$backupRootDir" -type d -maxdepth 2 -empty -print0 2>/dev/null | xargs -0 rmdir
+find "$backupRootDir" -type d -maxdepth 1 -empty -print0 2>/dev/null | xargs -0 rmdir
 
 # Remove old CloverPrefpane
 pkg='@CLOVER_PACKAGE_IDENTITY@.cloverprefpane'
